---
# Per environment values which override defaults in hmpps-prisoner-facing-lwp-poc-ui/values.yaml

generic-service:
  ingress:
    host: prisoner-facing-lwp-poc.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://prisoner-facing-lwp-poc.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    EDUCATION_AND_WORK_PLAN_API_URL: 'https://learningandworkprogress-api.hmpps.service.justice.gov.uk'
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-support-additional-needs-prod
