---
# Per environment values which override defaults in hmpps-prisoner-facing-lwp-poc-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    hosts:
      - prisoner-facing-lwp-poc-dev.hmpps.service.justice.gov.uk
      - shared.prisoner-facing-lwp-poc-dev.hmpps.service.justice.gov.uk
      - kiosk.prisoner-facing-lwp-poc-dev.hmpps.service.justice.gov.uk
      - private.prisoner-facing-lwp-poc-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '00 21 * * 1-5' # Stop at 9.00pm UTC Monday-Friday

  env:
    INGRESS_URL: "https://prisoner-facing-lwp-poc-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    LAUNCHPAD_AUTH_URL: "https://launchpad-auth-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    EDUCATION_AND_WORK_PLAN_API_URL: 'https://learningandworkprogress-api-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-support-additional-needs-dev
